version: "3.9"

services:
  glpi:
    image: diouxx/glpi:latest
    container_name: glpi
    ports:
      - "8080:80"
    environment:
      - TZ=UTC
    depends_on:
      - db
    volumes:
      - glpi_data:/var/www/html
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: glpi_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi_user
      MYSQL_PASSWORD: glpi_password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    restart: unless-stopped

volumes:
  glpi_data:
  db_data:
